# 一些python操作技巧
    和tensor操作相关

In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
x.shape
print(x.shape)
x.numel()
print(x)
X=x.reshape(3,4)
X

torch.Size([12])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
torch.randn(3,4)

tensor([[-1.1262, -0.5940,  0.0906,  1.1345],
        [-0.5573, -1.3159, -1.0977, -0.4194],
        [-1.2478,  1.1081, -0.2153, -1.9699]])

In [12]:
torch.tensor([[12,313],[22,190]])

tensor([[ 12, 313],
        [ 22, 190]])

In [13]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])

print(x+y)
print(x-y)
print(x*y)
print(x**y)

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([ 1.,  4., 16., 64.])


In [15]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])


In [16]:
# 行拼接
torch.cat((X,Y),dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [17]:
# 列拼接
torch.cat((X,Y),dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [18]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [19]:
X.sum()

tensor(66.)

In [20]:
# 广播机制
a= torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))

a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [21]:
x[::2]

tensor([1., 4.])

In [22]:
A= X.numpy()
B= torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [23]:
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)